backoff_factor: 1.5
bridge_inbox:
  check_interval: 1
  path: test_runtime\bridge_inbox
  pending_file: pending_requests.json
cursor_window_title: Test Cursor
max_retries: 2
page_load_wait: 1
paste_delay: 0.1
response_wait: 1
session_timeout: 5
user_data_dir: test_runtime\chrome_profile
