tasks:
  - task_id: UNIFY-MAILBOX-DATACLASS-001
    description: "Create a shared AgentEvent dataclass for inbox and devlog entries; refactor init_mailbox, AgentOperations, and DevlogManager to consume it."
    priority: HIGH
    agent: Agent-1

  - task_id: CENTRAL-DEVLOG-DISPATCHER-002
    description: "Implement EventBus in core/events.py; fire 'devlog_written' events in DevlogManager and subscribe RedditStrategy to auto-post."
    priority: HIGH
    agent: Agent-2

  - task_id: REUSABLE-INBOX-UTILITY-003
    description: "Extract inbox/status JSON I/O into core/mailbox_utils.py; refactor MessageProcessor, AgentOperations, and CLI/GUI to use it."
    priority: MEDIUM
    agent: Agent-3

  - task_id: METADATA-LINKING-DEVLOG-004
    description: "After social post in RedditStrategy, update event metadata with social_url in status.json via new mailbox_utils helper."
    priority: MEDIUM
    agent: Agent-4

  - task_id: SELF-SCHEDULING-MAINTENANCE-005
    description: "Enable agents to auto-enqueue REPAIR or BACKUP messages after N tasks or on errors based on AgentConfig."
    priority: LOW
    agent: Agent-5
