# StealthBrowser Bridge Configuration

# Browser Settings
headless: false
window_size: [1920, 1080]
page_load_wait: 30
element_wait: 10
response_wait: 60
paste_delay: 0.1

# User Data Directory
user_data_dir: runtime/browser_data

# Window Title
cursor_window_title: "StealthBrowser"

# Health Check Settings
health_check_interval: 30

# Cookie Settings
cookies:
  enabled: true
  file: runtime/cookies/stealth.json
  encryption_key: ${STEALTH_COOKIE_KEY}

# Stealth Settings
stealth:
  enabled: true
  user_agent_rotation: true
  fingerprint_randomization: true
  timing_randomization: true
  proxy_rotation: false

# Platform Settings
platforms:
  codex:
    url: "https://chatgpt.com/codex"
    selectors:
      input: "textarea[data-id='root']"
      submit: "button[data-id='submit']"
      response: "div[data-id='response']"
  chatgpt:
    url: "https://chat.openai.com"
    selectors:
      input: "textarea[data-id='root']"
      submit: "button[data-id='submit']"
      response: "div[data-id='response']"

# Logging Settings
logging:
  level: INFO
  file: runtime/logs/stealth_browser.log
  max_size: 10485760  # 10MB
  backup_count: 5

# Performance Settings
performance:
  max_retries: 3
  backoff_factor: 2.0
  connection_pool_size: 10
  request_timeout: 30

# Security Settings
security:
  rate_limit:
    enabled: true
    requests_per_minute: 60
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
  validation:
    ssl_verify: true
    certificate_check: true 