repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast  # Basic syntax check
    -   id: check-merge-conflict  # Prevent merge conflicts
    -   id: detect-private-key  # Security check

-   repo: local
    hooks:
    -   id: run-tests
        name: Run Tests
        entry: pytest tests/ -v
        language: system
        pass_filenames: false
        always_run: true

    -   id: run-scanner
        name: Run Project Scanner
        entry: python -m scanner.scanner --project-root . --ignore "venv,__pycache__,node_modules" --categorize-agents
        language: system
        pass_filenames: false
        always_run: true

    -   id: check-duplication
        name: Check Code Duplication
        entry: python -m scanner.analyzers.quality_analyzer --check-duplication
        language: system
        pass_filenames: false
        always_run: true

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"] 