alpaca:
  key:    "YOUR_KEY"
  secret: "YOUR_SECRET"
  paper:  true

trade:
  symbol: TSLA
  risk_per_trade_pct: 1.0        # % of equity
  max_positions: 3
  mc_paths: 5000                 # Monte-Carlo sims
  mc_days: 5                     # horizon in trading days
  min_pop: 0.55                  # POP threshold
  max_spread: 0.15               # $ width filter
  order_type: "limit"
  slippage: 0.05                 # $ pad on entry/exit
  hedge_delta: false
