name: dreamos-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pytest pytest-asyncio black==23.7.0 ruff==0.4.4 pytest-cov
      - name: Run pre-commit (Black + Ruff)
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Run resume-v2 tests
        run: pytest --maxfail=1 --quiet tests/core/resumer_v2 