name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Check for large modules
      run: |
        python tools/find_large_modules.py \
          --base dreamos/ \
          --limit 300 \
          --exclude "**/__init__.py" "**/tests/**" "**/migrations/**" \
          --fail-on-hit
        
    - name: Run unit tests with coverage
      run: |
        python -m pytest tests/unit --cov=dreamos --cov-append
        
    - name: Run integration tests with coverage
      run: |
        python -m pytest tests/integration --cov=dreamos --cov-append
        
    - name: Generate coverage report (fail under 75%)
      run: |
        python -m coverage xml
        python -m coverage report --fail-under=75
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        
    - name: Generate test badge
      if: success()
      run: |
        echo "::set-output name=status::passed"
        echo "::set-output name=color::green"
      id: badge
      
    - name: Update README badge
      if: success()
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: your-gist-id
        filename: test-status.json
        label: tests
        message: ${{ steps.badge.outputs.status }}
        color: ${{ steps.badge.outputs.color }} 